import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div
          className="min-h-screen bg-cover bg-center flex flex-col"
          style={{ backgroundImage: "url('/homebg.png')" }}
        >
          <div className="w-full max-w-4xl mx-auto p-6">
            <div className="card-like bg-white/85 dark:bg-black/60 backdrop-blur-sm">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
